-- DATABASE_SNAPSHOT_RELATIONSHIPS_PART2.sql
-- Primary key columns snapshot: shows the main ID for every table
-- To regenerate, run this query in Supabase SQL editor:
--
-- SELECT
--     tc.table_name,
--     kcu.column_name AS primary_key_column
-- FROM
--     information_schema.table_constraints AS tc
--     JOIN information_schema.key_column_usage AS kcu
--       ON tc.constraint_name = kcu.constraint_name
--       AND tc.table_schema = kcu.table_schema
-- WHERE tc.constraint_type = 'PRIMARY KEY'
--   AND tc.table_schema = 'public'
-- ORDER BY tc.table_name;
--
-- Copy ALL contents of this file and run as a single query to get the primary key columns.
