version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
  playwright:
    image: mcr.microsoft.com/playwright:v1.44.0-jammy
    depends_on:
      - app
    volumes:
      - ./:/app
    working_dir: /app
    command: tail -f /dev/null
