name: Web CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  web-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Yarn 4
        run: |
          corepack enable && corepack prepare yarn@4.9.2 --activate
          yarn install --immutable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Set SUPABASE env vars (dummy if secrets missing)
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-http://localhost}" >> $GITHUB_ENV
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-public-anon-key}" >> $GITHUB_ENV
          echo "SUPABASE_URL=${SUPABASE_URL:-http://localhost}" >> $GITHUB_ENV
          echo "SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-public-anon-key}" >> $GITHUB_ENV
      - name: Build web application
        run: yarn workspace web build
      - name: Run web tests
        run: yarn workspace web test
      - name: Run web linting
        run: yarn workspace web lint

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Yarn 4
        run: |
          corepack enable && corepack prepare yarn@4.9.2 --activate
          yarn install --immutable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install Playwright browsers
        run: yarn workspace web playwright install --with-deps
      - name: Check for E2E tests
        id: check_e2e
        run: |
          if compgen -G "packages/web/e2e/**/*.spec.*" > /dev/null; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi
      - name: Run E2E tests
        if: steps.check_e2e.outputs.found == 'true'
        run: yarn workspace web playwright test
