name: Web CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  web-build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Build web application
      run: yarn workspace web build
    
    - name: Run web tests
      run: yarn workspace web test
    
    - name: Run web linting
      run: yarn workspace web lint

  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Enable Corepack
      run: corepack enable
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    
    - name: Install dependencies
      run: yarn install --immutable
    
    - name: Install Playwright browsers
      run: yarn workspace web playwright install --with-deps
    
    - name: Run E2E tests
      run: yarn workspace web playwright test
    
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: packages/web/playwright-report/
        retention-days: 30
